services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command:  sh -c "npm i && npm run db:push && npm run dev"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./:/home
      - /home/node_modules
    networks:
      - baseful-network
  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=baseful
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - baseful-network

volumes:
  postgres_data:

networks:
  baseful-network:
    driver: bridge